(()=>{
const CLOSED=new Set(['finalizada','cancelada']);
const AREAS=[['logistica','Logística'],['mantenimiento','Mantenimiento'],['automotor','Automotor'],['almacen','Almacén'],['servicios','Servicios'],['limpieza','Limpieza'],['personal','Personal'],['bienes','Bienes']];
const ELEMENTOS=[
 ['Gazebos',/Gazebos?\s*[:x-]?\s*(\d+)/i],['Sillas',/Sillas?\s*[:x-]?\s*(\d+)/i],['Mesas',/Mesas?\s*[:x-]?\s*(\d+)/i],['Manteles',/Manteles?\s*[:x-]?\s*(\d+)/i],['Tablones',/Tabl[oó]nes?\s*[:x-]?\s*(\d+)/i],['Caballetes',/Caballetes?\s*[:x-]?\s*(\d+)/i],['Pava eléctrica',/Pava\s+el[eé]ctrica\s*[:x-]?\s*(\d+)/i],['Alargues',/Alargues?\s*[:x-]?\s*(\d+)/i],['Zapatillas eléctricas',/Zapatillas?\s+el[eé]ctricas?\s*[:x-]?\s*(\d+)/i],['Bidones de agua',/Bidones?(?:\s+de\s+agua)?\s*[:x-]?\s*(\d+)/i],['Dispenser',/Dispensers?\s*[:x-]?\s*(\d+)/i],['Té',/T[eé]\s*[:x-]?\s*(\d+)/i],['Mate cocido',/Mate\s+cocido\s*[:x-]?\s*(\d+)/i],['Café',/Caf[eé]\s*[:x-]?\s*(\d+)/i],['Azúcar',/Az[uú]car\s*[:x-]?\s*(\d+)/i],['Removedores',/Removedores?\s*[:x-]?\s*(\d+)/i],['Edulcorante',/Edulcorantes?\s*[:x-]?\s*(\d+)/i],['Vasos térmicos',/Vasos?\s+t[eé]rmicos?\s*[:x-]?\s*(\d+)/i],['Vasos telgopor',/Vasos?\s+telgopor\s*[:x-]?\s*(\d+)/i],['Precintos',/Precintos?\s*[:x-]?\s*(\d+)/i],['Alambre',/Alambre\s*[:x-]?\s*(\d+)/i],['Herramientas',/Herramientas?\s*[:x-]?\s*(\d+)/i],['Moledora',/Moledoras?\s*[:x-]?\s*(\d+)/i],['Agujereadora',/Agujereadoras?\s*[:x-]?\s*(\d+)/i],['Hidrolavadora',/Hidrolavadoras?\s*[:x-]?\s*(\d+)/i],['Aspiradora',/Aspiradoras?\s*[:x-]?\s*(\d+)/i]
];
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
const state=n=>n.querySelector('.estado')?.value||'';
const priority=n=>n.querySelector('.prio')?.value||'normal';
const code=n=>n.querySelector('.request-code')?.textContent?.trim()||'Solicitud';
const area=n=>norm((n.querySelector('.request-sub')?.textContent||'').split('·')[0].trim());
const isAdmin=()=>[...document.querySelectorAll('h2')].some(h=>/Panel\s*·.*\(admin\)/i.test(h.textContent||''));
const prettyArea=k=>AREAS.find(a=>a[0]===k)?.[1]||k;
const ymd=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const fechaISO=s=>{if(!s)return'';const a=String(s).trim();if(/^\d{4}-\d{2}-\d{2}$/.test(a))return a;const m=a.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:''};
const pedidoDe=t=>ELEMENTOS.flatMap(([nombre,re])=>{const m=String(t||'').match(re);return m&&Number(m[1])>0?[[nombre,Number(m[1])]]:[]});
function css(){
 if(document.querySelector('#adminDashboardStyles'))return;
 const s=document.createElement('style');s.id='adminDashboardStyles';s.textContent=`
 body.admin-pro #farea{display:none!important}
 .admin-pro-dashboard{margin:22px 0 4px}.admin-pro-head h3{margin:0;font-size:22px}.admin-pro-head p{margin:4px 0 0;color:#687383}
 .admin-pro-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:16px 0 24px}.admin-pro-stat{border:1px solid #dce3ea;border-radius:14px;background:#f7f9fb;padding:14px}.admin-pro-stat span{display:block;color:#687383;font-size:13px;font-weight:700}.admin-pro-stat strong{display:block;font-size:30px;line-height:1;margin:7px 0}.admin-pro-stat small{color:#7b8492}.admin-pro-stat.urgent strong{color:#a12626}
 .admin-pro-section{display:flex;justify-content:space-between;gap:10px;align-items:end;margin:0 0 10px}.admin-pro-section h3{margin:0}.admin-pro-section span{font-size:13px;color:#687383}
 .admin-pro-areas{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.admin-pro-area{text-align:left;padding:16px;border:1px solid #dce3ea;border-radius:14px;background:#fff;min-height:105px}.admin-pro-area:active{transform:scale(.99)}.admin-pro-area-top{display:flex;justify-content:space-between;align-items:center;gap:10px}.admin-pro-area-top span{font-size:17px;font-weight:750}.admin-pro-area-top strong{font-size:28px}.admin-pro-area-meta{margin-top:8px;font-size:12px;line-height:1.4;color:#687383}
 .admin-pro-history,.admin-pro-agenda{width:100%;margin-top:12px;display:flex;justify-content:space-between;align-items:center;font-weight:750;padding:14px}.admin-pro-agenda{background:#102033;color:white}.admin-pro-areahead{display:flex;gap:12px;align-items:center;margin:20px 0 14px}.admin-pro-areahead h3{margin:0;font-size:22px}.admin-pro-areahead p{margin:3px 0 0;color:#687383}.admin-pro-group-title{display:flex;justify-content:space-between;align-items:center;margin:18px 0 10px}.admin-pro-group-title h3{margin:0}.admin-pro-count{background:#102033;color:#fff;border-radius:999px;min-width:34px;padding:6px 10px;text-align:center}.admin-pro-list{display:grid;gap:10px}.admin-pro-closed{margin-top:22px;border-top:2px solid #e4e8ed;padding-top:16px}.admin-pro-toggle{width:100%;display:flex;justify-content:space-between;font-weight:750}.admin-pro-empty{padding:18px;border:1px dashed #d6dde5;border-radius:12px;color:#687383;text-align:center}
 .agenda-controls{display:flex;gap:8px;flex-wrap:wrap;margin:14px 0}.agenda-controls button.active{background:#102033;color:#fff}.agenda-filters{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px;margin-bottom:12px}.agenda-actions{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:18px}.agenda-day{margin:18px 0}.agenda-day h3{text-transform:capitalize;margin:0 0 8px;padding-bottom:7px;border-bottom:1px solid #e3e8ee}.agenda-item{display:grid;grid-template-columns:68px 1fr;gap:12px;padding:10px 2px;border-bottom:1px solid #edf0f3}.agenda-time{font-weight:800}.agenda-code{font-weight:800}.agenda-meta{font-size:13px;color:#687383;margin-top:5px}.agenda-pedido{list-style:none;margin:9px 0 4px;padding:0;max-width:360px;border-top:1px solid #edf0f3}.agenda-pedido li{display:flex;justify-content:space-between;gap:18px;padding:5px 0;border-bottom:1px solid #edf0f3}.agenda-pedido strong{font-weight:800}.agenda-empty{padding:20px;text-align:center;color:#687383;border:1px dashed #d6dde5;border-radius:12px}
 @media(max-width:700px){.admin-pro-stats{grid-template-columns:repeat(2,1fr);gap:8px}.admin-pro-stat{padding:12px}.admin-pro-stat strong{font-size:26px}.admin-pro-areas{grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.admin-pro-area{padding:13px;min-height:96px}.admin-pro-area-top span{font-size:15px}.admin-pro-area-top strong{font-size:24px}.admin-pro-areahead{align-items:flex-start;flex-direction:column}.agenda-filters{grid-template-columns:1fr}.agenda-item{grid-template-columns:58px 1fr}}
 @media print{body *{visibility:hidden!important}#tasks,#tasks *{visibility:visible!important}#tasks{position:absolute;left:0;top:0;width:100%}.agenda-controls,.agenda-filters,.agenda-actions,.admin-pro-areahead button{display:none!important}}
 `;document.head.appendChild(s);
}
function prepare(){
 const tasks=document.querySelector('#tasks');
 if(!tasks||tasks.dataset.adminPro==='1'||!isAdmin())return;
 const nodes=[...tasks.querySelectorAll('.request')];if(!nodes.length)return;
 tasks.dataset.adminPro='1';document.body.classList.add('admin-pro');css();const f=document.querySelector('#farea');if(f)f.style.display='none';
 const items=nodes.map(node=>({node,area:area(node),state:state(node),priority:priority(node),code:code(node),text:(node.textContent||node.innerText||'').replace(/\s+/g,' ').trim(),sub:(node.querySelector('.request-sub')?.textContent||'').split('·').map(x=>x.trim())}));nodes.forEach(n=>n.remove());
 const active=()=>items.filter(x=>!CLOSED.has(x.state));const closed=()=>items.filter(x=>CLOSED.has(x.state));const byArea=(key,closedFlag)=>items.filter(x=>x.area===key&&(closedFlag?CLOSED.has(x.state):!CLOSED.has(x.state)));
 function mountList(container,list,empty){container.innerHTML='';if(!list.length){container.innerHTML=`<div class="admin-pro-empty">${empty}</div>`;return}list.forEach(x=>container.appendChild(x.node));}
 function home(){
  const a=active(),c=closed(),nuevas=a.filter(x=>x.state==='nueva').length,ejec=a.filter(x=>x.state==='en_ejecucion').length,urg=a.filter(x=>x.priority==='urgente').length;
  const cards=AREAS.map(([key,name])=>{const l=byArea(key,false),u=l.filter(x=>x.priority==='urgente').length,w=l.filter(x=>x.state==='en_espera').length;return `<button class="admin-pro-area" data-area="${key}"><div class="admin-pro-area-top"><span>${name}</span><strong>${l.length}</strong></div><div class="admin-pro-area-meta">${l.length===1?'1 solicitud activa':l.length+' solicitudes activas'}${u?` · ${u} urgente${u===1?'':'s'}`:''}${w?` · ${w} en espera`:''}</div></button>`}).join('');
  tasks.innerHTML=`<section class="admin-pro-dashboard"><div class="admin-pro-head"><h3>Resumen general</h3><p>Vista de gestión por área</p></div><div class="admin-pro-stats"><div class="admin-pro-stat"><span>Pendientes</span><strong>${a.length}</strong><small>${nuevas} nuevas</small></div><div class="admin-pro-stat"><span>En ejecución</span><strong>${ejec}</strong><small>trabajos activos</small></div><div class="admin-pro-stat urgent"><span>Urgentes</span><strong>${urg}</strong><small>requieren atención</small></div><div class="admin-pro-stat"><span>Finalizados</span><strong>${c.length}</strong><small>historial</small></div></div><div class="admin-pro-section"><h3>Áreas</h3><span>Solicitudes activas</span></div><div class="admin-pro-areas">${cards}</div><button class="admin-pro-agenda" id="adminAgenda"><span>Agenda operativa</span><strong>→</strong></button><button class="admin-pro-history" id="adminHistory"><span>Historial / Finalizados</span><strong>${c.length} →</strong></button></section>`;
  tasks.querySelectorAll('.admin-pro-area').forEach(b=>b.onclick=()=>areaView(b.dataset.area));tasks.querySelector('#adminHistory').onclick=history;tasks.querySelector('#adminAgenda').onclick=agenda;
 }
 function areaView(key){
  const name=prettyArea(key),a=byArea(key,false),c=byArea(key,true),urg=a.filter(x=>x.priority==='urgente').length;
  tasks.innerHTML=`<div class="admin-pro-areahead"><button id="adminBack">← Todas las áreas</button><div><h3>${name}</h3><p>${a.length} activas${urg?` · ${urg} urgente${urg===1?'':'s'}`:''}</p></div></div><div class="admin-pro-group-title"><h3>Pendientes / En curso</h3><span class="admin-pro-count">${a.length}</span></div><div id="adminActive" class="admin-pro-list"></div><div class="admin-pro-closed"><button id="adminClosedToggle" class="admin-pro-toggle"><span>Finalizados / Cancelados</span><span>${c.length} ▾</span></button><div id="adminClosed" class="admin-pro-list" hidden></div></div>`;
  tasks.querySelector('#adminBack').onclick=home;mountList(tasks.querySelector('#adminActive'),a,'No hay solicitudes pendientes en esta área.');const cl=tasks.querySelector('#adminClosed');mountList(cl,c,'No hay solicitudes finalizadas en esta área.');cl.hidden=true;tasks.querySelector('#adminClosedToggle').onclick=e=>{cl.hidden=!cl.hidden;e.currentTarget.lastElementChild.textContent=`${c.length} ${cl.hidden?'▾':'▴'}`};
 }
 function history(){const c=closed();tasks.innerHTML=`<div class="admin-pro-areahead"><button id="adminBack">← Tablero</button><div><h3>Historial / Finalizados</h3><p>${c.length} solicitudes cerradas</p></div></div><div id="adminHistoryList" class="admin-pro-list"></div>`;tasks.querySelector('#adminBack').onclick=home;mountList(tasks.querySelector('#adminHistoryList'),c,'Todavía no hay solicitudes cerradas.');}
 function movimientos(x){
  const out=[],t=x.text;
  const add=(fecha,hora,mov)=>{const f=fechaISO(fecha);if(f)out.push({...x,fecha:f,hora:hora||'',movimiento:mov,pedido:pedidoDe(t)})};
  const fecha='(\\d{4}-\\d{2}-\\d{2}|\\d{1,2}[\\/-]\\d{1,2}[\\/-]\\d{4})';
  const en=t.match(new RegExp(`Entrega\\s*${fecha}(?:\\s+(\\d{2}:\\d{2}))?`,'i'));
  const re=t.match(new RegExp(`Retiro(?:\\s*\\/\\s*devoluci[oó]n)?\\s*${fecha}(?:\\s+(\\d{2}:\\d{2}))?`,'i'));
  if(en)add(en[1],en[2],'Entrega');if(re)add(re[1],re[2],'Retiro / devolución');
  if(!out.length){const f=t.match(new RegExp(`(?:Fecha requerida|Fecha de entrega|Fecha relacionada|Fecha)\\s*:?\\s*${fecha}(?:\\s+(\\d{2}:\\d{2}))?`,'i'))||t.match(new RegExp(`${fecha}(?:\\s+(\\d{2}:\\d{2}))?`));if(f)add(f[1],f[2],'Tarea')}
  return out;
 }
 const agendaItems=()=>items.flatMap(movimientos).sort((a,b)=>(a.fecha+a.hora).localeCompare(b.fecha+b.hora));
 function rango(tipo){const h=new Date();h.setHours(0,0,0,0);if(tipo==='hoy')return[ymd(h),ymd(h)];if(tipo==='manana'){const m=new Date(h);m.setDate(m.getDate()+1);return[ymd(m),ymd(m)]}const i=new Date(h);const dow=(i.getDay()+6)%7;i.setDate(i.getDate()-dow);const f=new Date(i);f.setDate(f.getDate()+6);return[ymd(i),ymd(f)]}
 function agenda(){const [d0,h0]=rango('semana');tasks.innerHTML=`<div class="admin-pro-areahead"><button id="adminBack">← Tablero</button><div><h3>Agenda operativa</h3><p>Solicitudes ordenadas por fecha y hora</p></div></div><div class="agenda-controls"><button data-r="hoy">Hoy</button><button data-r="manana">Mañana</button><button data-r="semana" class="active">Esta semana</button></div><div class="agenda-filters"><label>Desde<input id="agendaDesde" type="date" value="${d0}"></label><label>Hasta<input id="agendaHasta" type="date" value="${h0}"></label><label>Área<select id="agendaArea"><option value="">Todas</option>${AREAS.map(([k,n])=>`<option value="${k}">${n}</option>`).join('')}</select></label></div><div class="agenda-actions"><button id="agendaCsv">Exportar CSV</button><button id="agendaPrint">Imprimir / PDF</button></div><div id="agendaLista"></div>`;tasks.querySelector('#adminBack').onclick=home;
  const render=()=>{const d=tasks.querySelector('#agendaDesde').value,h=tasks.querySelector('#agendaHasta').value,a=tasks.querySelector('#agendaArea').value;const lista=agendaItems().filter(x=>(!d||x.fecha>=d)&&(!h||x.fecha<=h)&&(!a||x.area===a));tasks.dataset.agendaLista=JSON.stringify(lista.map(x=>({fecha:x.fecha,hora:x.hora,area:x.area,codigo:x.code,tipo:x.sub[1]||'',movimiento:x.movimiento,lugar:x.sub.slice(2).join(' · '),pedido:x.pedido,estado:x.state})));const box=tasks.querySelector('#agendaLista');if(!lista.length){box.innerHTML='<div class="agenda-empty">No hay movimientos para las fechas seleccionadas.</div>';return}const g={};lista.forEach(x=>(g[x.fecha]??=[]).push(x));box.innerHTML=Object.entries(g).map(([f,arr])=>`<section class="agenda-day"><h3>${new Date(f+'T12:00:00').toLocaleDateString('es-AR',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'})}</h3>${arr.map(x=>`<div class="agenda-item"><div class="agenda-time">${esc(x.hora||'—')}</div><div><div class="agenda-code">${esc(x.code)} · ${esc(x.movimiento)}</div><div>${esc(prettyArea(x.area))} · ${esc(x.sub[1]||'')}${x.sub.slice(2).length?` · ${esc(x.sub.slice(2).join(' · '))}`:''}</div>${x.pedido?.length?`<ul class="agenda-pedido">${x.pedido.map(([n,c])=>`<li><span>${esc(n)}</span><strong>${c}</strong></li>`).join('')}</ul>`:''}<div class="agenda-meta">Estado: ${esc(x.state||'-')}</div></div></div>`).join('')}</section>`).join('')};
  tasks.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>{tasks.querySelectorAll('[data-r]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const [d,h]=rango(b.dataset.r);tasks.querySelector('#agendaDesde').value=d;tasks.querySelector('#agendaHasta').value=h;render()});tasks.querySelector('#agendaDesde').onchange=render;tasks.querySelector('#agendaHasta').onchange=render;tasks.querySelector('#agendaArea').onchange=render;tasks.querySelector('#agendaPrint').onclick=()=>window.print();tasks.querySelector('#agendaCsv').onclick=()=>{const lista=JSON.parse(tasks.dataset.agendaLista||'[]');const cab=['Fecha','Hora','Área','Código','Tipo','Movimiento','Lugar / destino','Pedido','Estado'];const rows=lista.map(x=>[x.fecha,x.hora,prettyArea(x.area),x.codigo,x.tipo,x.movimiento,x.lugar,(x.pedido||[]).map(([n,c])=>`${n}: ${c}`).join(' | '),x.estado]);const val=v=>`"${String(v??'').replaceAll('"','""')}"`;const csv='\uFEFF'+[cab,...rows].map(r=>r.map(val).join(';')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`agenda-patrimonio-${ymd(new Date())}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};render();}
 home();
}
const ob=new MutationObserver(()=>setTimeout(prepare,0));ob.observe(document.documentElement,{childList:true,subtree:true});setInterval(prepare,800);
})();