-- SOLICITUDES PATRIMONIO V2
-- Ejecutar una sola vez en Supabase SQL Editor.

create table if not exists public.historial_solicitudes (
  id bigint generated by default as identity primary key,
  solicitud_id uuid not null references public.solicitudes(id) on delete cascade,
  usuario_id uuid references public.usuarios(id) on delete set null,
  accion text not null,
  detalle jsonb not null default '{}'::jsonb,
  creado_en timestamptz not null default now()
);

alter table public.historial_solicitudes enable row level security;

drop policy if exists "historial autenticado lectura" on public.historial_solicitudes;
create policy "historial autenticado lectura" on public.historial_solicitudes
for select to authenticated using (public.puede_ver_solicitud(solicitud_id));

grant select on public.historial_solicitudes to authenticated;
grant usage, select on sequence public.historial_solicitudes_id_seq to authenticated;

-- Crear solicitudes públicas mediante RPC: devuelve el código sin abrir SELECT público sobre la tabla.
create or replace function public.crear_solicitud_publica(
  p_modulo text,
  p_tipo text,
  p_solicitante text,
  p_lugar text,
  p_telefono text,
  p_email text,
  p_fecha_requerida date,
  p_descripcion text,
  p_datos jsonb
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_codigo text;
begin
  if coalesce(trim(p_solicitante),'') = '' or coalesce(trim(p_telefono),'') = '' then
    raise exception 'Faltan solicitante o teléfono';
  end if;

  insert into public.solicitudes(
    codigo, modulo, tipo, solicitante, lugar, telefono, email,
    fecha_requerida, descripcion, estado, prioridad, datos
  ) values (
    'TEMP', lower(p_modulo), p_tipo, trim(p_solicitante), nullif(trim(p_lugar),''),
    trim(p_telefono), nullif(trim(p_email),''), p_fecha_requerida,
    nullif(trim(p_descripcion),''), 'nueva', 'normal', coalesce(p_datos,'{}'::jsonb)
  ) returning codigo into v_codigo;

  return v_codigo;
end;
$$;

revoke all on function public.crear_solicitud_publica(text,text,text,text,text,text,date,text,jsonb) from public;
grant execute on function public.crear_solicitud_publica(text,text,text,text,text,text,date,text,jsonb) to anon, authenticated;

-- Nota interna + historial.
create or replace function public.registrar_movimiento(
  p_solicitud_id uuid,
  p_accion text,
  p_detalle jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_usuario uuid;
begin
  v_usuario := public.mi_usuario_id();
  if v_usuario is null or not public.puede_ver_solicitud(p_solicitud_id) then
    raise exception 'Sin permiso';
  end if;
  insert into public.historial_solicitudes(solicitud_id,usuario_id,accion,detalle)
  values(p_solicitud_id,v_usuario,p_accion,coalesce(p_detalle,'{}'::jsonb));
end;
$$;
revoke all on function public.registrar_movimiento(uuid,text,jsonb) from public;
grant execute on function public.registrar_movimiento(uuid,text,jsonb) to authenticated;

-- Actualizar estado/prioridad con historial.
create or replace function public.actualizar_gestion_solicitud(
  p_solicitud_id uuid,
  p_estado text default null,
  p_prioridad text default null,
  p_nota text default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_usuario uuid; v_rol text;
begin
  v_usuario := public.mi_usuario_id();
  select rol into v_rol from public.usuarios where id=v_usuario and activo=true;
  if v_usuario is null or not public.puede_ver_solicitud(p_solicitud_id) then raise exception 'Sin permiso'; end if;

  update public.solicitudes set
    estado = coalesce(p_estado,estado),
    prioridad = coalesce(p_prioridad,prioridad),
    actualizado_en = now()
  where id=p_solicitud_id;

  insert into public.historial_solicitudes(solicitud_id,usuario_id,accion,detalle)
  values(p_solicitud_id,v_usuario,'gestion',jsonb_build_object('estado',p_estado,'prioridad',p_prioridad,'nota',p_nota));
end;
$$;
revoke all on function public.actualizar_gestion_solicitud(uuid,text,text,text) from public;
grant execute on function public.actualizar_gestion_solicitud(uuid,text,text,text) to authenticated;

-- Seguimiento operativo de Logística se guarda dentro de datos.seguimiento_logistico.
create or replace function public.actualizar_seguimiento_logistico(
  p_solicitud_id uuid,
  p_etapa text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_usuario uuid; v_nombre text;
begin
  if p_etapa not in ('pedido_recibido','preparando','salio_deposito','entregado','pendiente_retiro','devuelto') then
    raise exception 'Etapa inválida';
  end if;
  v_usuario := public.mi_usuario_id();
  if v_usuario is null or not public.puede_ver_solicitud(p_solicitud_id) then raise exception 'Sin permiso'; end if;
  select nombre into v_nombre from public.usuarios where id=v_usuario;

  update public.solicitudes
  set datos = jsonb_set(coalesce(datos,'{}'::jsonb),'{seguimiento_logistico}',
      jsonb_build_object('etapa',p_etapa,'fecha',now(),'usuario_id',v_usuario,'usuario',v_nombre),true),
      actualizado_en=now()
  where id=p_solicitud_id and modulo='logistica';

  insert into public.historial_solicitudes(solicitud_id,usuario_id,accion,detalle)
  values(p_solicitud_id,v_usuario,'seguimiento_logistico',jsonb_build_object('etapa',p_etapa));
end;
$$;
revoke all on function public.actualizar_seguimiento_logistico(uuid,text) from public;
grant execute on function public.actualizar_seguimiento_logistico(uuid,text) to authenticated;

-- Asignación: admin asigna; supervisores ven pero no reasignan.
create or replace function public.asignar_responsables(
  p_solicitud_id uuid,
  p_usuario_ids uuid[]
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare v_usuario uuid; v_es_admin boolean;
begin
  v_usuario := public.mi_usuario_id();
  select exists(select 1 from public.usuarios where id=v_usuario and activo=true and rol='admin') into v_es_admin;
  if not v_es_admin then raise exception 'Solo el administrador puede asignar responsables'; end if;

  delete from public.solicitud_responsables where solicitud_id=p_solicitud_id;
  if coalesce(array_length(p_usuario_ids,1),0)>0 then
    insert into public.solicitud_responsables(solicitud_id,usuario_id,tipo)
    select p_solicitud_id,x,'responsable' from unnest(p_usuario_ids) x;
    update public.solicitudes set estado=case when estado='nueva' then 'asignada' else estado end, actualizado_en=now() where id=p_solicitud_id;
  end if;
  insert into public.historial_solicitudes(solicitud_id,usuario_id,accion,detalle)
  values(p_solicitud_id,v_usuario,'asignacion',jsonb_build_object('usuarios',coalesce(to_jsonb(p_usuario_ids),'[]'::jsonb)));
end;
$$;
revoke all on function public.asignar_responsables(uuid,uuid[]) from public;
grant execute on function public.asignar_responsables(uuid,uuid[]) to authenticated;

-- Código de Mantenimiento. Usa pgcrypto ya configurado en extensions.
insert into public.configuracion(clave,valor)
values('codigo_mantenimiento',jsonb_build_object('hash',extensions.crypt('040301',extensions.gen_salt('bf'))))
on conflict(clave) do update set valor=excluded.valor, actualizado_en=now();

create or replace function public.validar_codigo_mantenimiento(p_codigo text)
returns boolean language sql security definer set search_path=public,extensions as $$
  select coalesce(extensions.crypt(p_codigo,valor->>'hash')=valor->>'hash',false)
  from public.configuracion where clave='codigo_mantenimiento';
$$;
revoke all on function public.validar_codigo_mantenimiento(text) from public;
grant execute on function public.validar_codigo_mantenimiento(text) to anon, authenticated;
